- hosts: "localhost"

  become: true

  roles:

    - role: db_prolog 
      vars:
        ctf_gameserver_db_pass_controller: 'xza'
        ctf_gameserver_db_pass_web: 'xza'
        ctf_gameserver_db_pass_checker: 'xza'
        ctf_gameserver_db_pass_submission: 'xza'
        ctf_gameserver_db_user_vpnstatus: 'xza'
        ctf_gameserver_db_pass_vpnstatus: 'xza'

    - role: web
      vars:
        ctf_gameserver_downloadpath: '/home/admin'
        ctf_gameserver_web_from_email: 'xzabala@uni.eus'
        ctf_gameserver_web_secret_key: 'xza'
        ctf_gameserver_web_admin_email: 'xza'
        ctf_gameserver_web_admin_pass: 'xza'

    - role: db_epilog

    - role: controller

    - role: submission
      vars:
        ctf_gameserver_db_pass_submission: 'xza'
        ctf_gameserver_flag_secret: 'xza'

    - role: checker

    - role: vpnstatus

